# Starting Over Notes
[Lena Davis-Jones]
Age = 26
Married = 4
Husband = 'Josh Davis'
Cupsize = 'E'
Weight = '160lbs'
Height = '5"2'
Measurements = '36F-34-40'
BestFriend = 'Natalie Logan'


[Josh Davis]
Age = 27
PassedAway = '-6 Months'


[Natalie Logan]
Age = 25
Maried = false
Husband = ''
Cupsize = 'DD'
Weight = '157lbs'
Height = '5"7'
Measurements = '34DD-32-38'
