# one_hot_summer.md notes

[Luna Baker]
age = 16
alias = Lucilla Starr
eye_color = blue
hair_color = black
height = 162 - 5'3
weight = 58 kg - 127lbs
measurements = 36DDD-27-39
boobs = real
shoes = 38 eu

best_friend =  Melissa

crush on =
uncle = Dave Miller (mothers side)
